const ASSETS_URL = "/assets/"
const FOCUSED_CLASS = "c-focused"
const COLLECTION_WIDTH = 500
const MOVIES_HEIGHT = 440
const MOVIE_LINE_HEIGHT = 310
const DEFAULT_BACKGROUND = "backgrounds/comedy_bg.jpg"

export const C = {
  ASSETS_URL,
  FOCUSED_CLASS,
  COLLECTION_WIDTH,
  MOVIES_HEIGHT,
  MOVIE_LINE_HEIGHT,
  DEFAULT_BACKGROUND
}
